openapi: 3.0.0
info:
  title: PetMeAPI
  description: Especificación de la API que expone los servicios provistos por el servidor de PetMe
  version: 0.5.1
  contact:
    name: Edson Manuel Carballo Vera
    email: edsonmanuelcarballovera@gmail.com
    url: https://twitter.com/EdsonManuelVera
servers:
  - description: Producción
    url: 'https://amigosinformaticos.ddns.net:42070'
paths:
  /login:
    $ref: './login.yaml'
  /adoptantes:
    $ref: './adoptantes.yaml'
  /adoptantes/{id_adoptante}:
    $ref: './adoptantes_id.yaml'
  /adoptantes/{id_adoptante}/imagen:
    $ref: './adoptantes_id_imagen.yaml'
  /refugios:
    $ref: './refugios.yaml'
  /refugios/{id_refugio}:
    $ref: './refugios_id.yaml'
  /mascotas:
    $ref: './mascotas.yaml'
  /mascotas/{id_mascota}:
    $ref: './mascotas_id.yaml'
  /mascotas/{id_mascota}/imagen:
    $ref: './mascotas_id_imagen.yaml'
  /mascotas/{id_mascota}/imagen/{id_imagen}:
    $ref: './mascotas_id_imagen_id.yaml'
  /solicitudes:
    $ref: './solicitud.yaml'