name: Test and build

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Copiar Repositorio
        uses: actions/checkout@v2

      - name: Configurar Pytest
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html pytest-dependency
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ejecucion de pruebas
        run: pytest tests --html=./reports/$(date '+%d-%m-%y').html --self-contained-html

      - name: Subir reporte
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Reporte PyTest
          path: ./reports

  generar_spec:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Copiar repositorio
        uses: actions/checkout@v2

      - name: Validar especificación
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: "validate api/PetMe.yaml"

      - name: Compilar especificación
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: bundle -o PetMeBundle.yaml -t yaml api/PetMe.yaml

      - name: Publicar especificación
        uses: Legion2/swagger-ui-action@v1
        with:
          output: specs
          spec-file: PetMeBundle.yaml

      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.EDSON_GITHUB_TOKEN }}
          publish_dir: specs

  buildx:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Copiar Repositorio
        uses: actions/checkout@v2

      - name: Login a Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.EDSON_DOCKERHUB_ID }}
          password: ${{ secrets.EDSON_DOCKERHUB_TOKEN }}

      - name: Configurar QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configurar buildx
        uses: docker/setup-buildx-action@v1

      - name: Construir con buildx
        run: |
          docker buildx build \
          --push \
          --tag amigosinformaticos/pet_me_api:latest \
          --platform linux/arm/v6 .