name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  buildx:
    if: ${{ github.event.label.name == 'build' }}
    runs-on: ubuntu-latest
    steps:
      - name: Copiar Repositorio
        uses: actions/checkout@v2

      - name: Login a Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.EDSON_DOCKERHUB_ID }}
          password: ${{ secrets.EDSON_DOCKERHUB_TOKEN }}

      - name: Configurar QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configurar buildx
        uses: docker/setup-buildx-action@v1

      - name: Construir con buildx
        run: |
          docker buildx build \
          --push \
          --tag amigosinformaticos/pet_me_api:latest \
          --platform linux/arm/v6 .
  fail_if_needed:
    if: ${{ !github.event.label.name == 'build' }}
    runs-on: ubuntu-latest
    steps:
      - name: Lanzar fallo
        run: exit 1